# Generated by Django 4.2.9 on 2024-03-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='productname',
            new_name='name',
        ),
    ]
